services:

  ws-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ID: node-1
      AUTH_VALIDATE_URL: http://java-backend:8080/internal/session/validate
      SESSION_COOKIE_NAME: session
      AUTH_TIMEOUT_MS: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_INGRESS_CHANNEL: ws:push
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
